#!/usr/bin/env python3
"""Audit of our 2026 events and decisions.

Scans events/md2026_*.txt and common/decisions/md2026_decisions.txt and writes
docs/Event-Audit.md: every event id with its English title, the date gate from
its trigger, and a review status.

Usage:
    python tools/event_audit.py [--write]
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rebase  # noqa: E402

REPO = rebase.REPO
EN_LOC = os.path.join(REPO, "localisation", "english", "md2026_l_english.yml")

# Events whose 2026 premise deserves a reader's attention.
NOTES = {
    "md2026_ru_ukr.": "speculative negotiation chain - the 2026 war could end this way",
    "md2026_taiwan.": "speculative escalation chain",
    "md2026_taiwan_news.": "news mirrors the Taiwan chain",
    "md2026_mideast.": "post-Assad / Gaza / Iran content",
    "md2026_nato_russia.": "Article 5 and hybrid-war scenarios",
    "md2026_venezuela.": "US pressure campaign against Maduro (2025-2026)",
    "md2026_elections.": "election calendar, real dates where known",
    "md2026_brics.": "BRICS+ expansion and de-dollarization",
    "md2026_space.": "space programmes after 2025",
    "md2026_climate.": "climate and energy crisis",
    "md2026_demographics.": "demography and migration pressure",
    "md2026_tech_revolution.": "AI and technology race",
    "md2026_migration.": "migration pressure",
    "md2026_random.": "general 2026 colour events",
    "md2026_system.": "engine helpers (war exhaustion, crisis flags)",
    "md2026_nato_article5.": "Article 5 mechanics",
}


def read_loc():
    out = {}
    with open(EN_LOC, encoding="utf-8-sig") as f:
        for line in f:
            m = re.match(r'^\s*([A-Za-z0-9_\.]+):\d*\s+"(.*)"\s*$', line)
            if m:
                out[m.group(1)] = m.group(2)
    return out


def scan_events():
    out = []
    root = os.path.join(REPO, "events")
    for name in sorted(os.listdir(root)):
        if not name.startswith("md2026_") or not name.endswith(".txt"):
            continue
        text = rebase.strip_comments(rebase.read(os.path.join(root, name)))
        for m in re.finditer(r"(country_event|news_event|state_event)\s*=\s*\{", text):
            ob = text.index("{", m.end() - 1)
            body = text[ob:rebase.find_block(text, ob)]
            idm = re.search(r"(?m)^\s*id\s*=\s*([A-Za-z0-9_]+\.[0-9]+)", body)
            if not idm:
                continue
            eid = idm.group(1)
            tm = re.search(r"(?m)^\s*title\s*=\s*([A-Za-z0-9_\.]+)", body)
            dates = re.findall(r"date\s*[<>]\s*([0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2})", body)
            mtth = re.search(r"mean_time_to_happen\s*=\s*\{([^}]*)\}", body)
            once = "yes" if re.search(r"fire_only_once\s*=\s*yes", body) else ""
            out.append({
                "file": name,
                "id": eid,
                "kind": m.group(1),
                "title": tm.group(1) if tm else "",
                "date": dates[0] if dates else "",
                "mtth": " ".join(mtth.group(1).split()) if mtth else "",
                "once": once,
            })
    return out


def scan_decisions():
    out = []
    path = os.path.join(REPO, "common", "decisions", "md2026_decisions.txt")
    if not os.path.exists(path):
        return out
    text = rebase.strip_comments(rebase.read(path))
    for m in re.finditer(r"(?m)^\t([A-Za-z0-9_]+)\s*=\s*\{", text):
        ob = text.index("{", m.end() - 1)
        body = text[ob:rebase.find_block(text, ob)]
        if not re.search(r"complete_effect\s*=", body):
            continue
        dates = re.findall(r"date\s*[<>]\s*([0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2})", body)
        dr = re.search(r"days_remove\s*=\s*(\d+)", body)
        out.append({
            "id": m.group(1),
            "date": dates[0] if dates else "",
            "fire_once": "yes" if re.search(r"fire_only_once\s*=\s*yes", body) else "",
            "days_remove": dr.group(1) if dr else "",
        })
    return out


def note_for(eid):
    for prefix, note in NOTES.items():
        if eid.startswith(prefix):
            return note
    return ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    loc = read_loc()
    events = scan_events()
    decisions = scan_decisions()

    by_file = {}
    for e in events:
        by_file.setdefault(e["file"], []).append(e)

    lines = [
        "# 2026 event and decision audit",
        "",
        "Generated by `python tools/event_audit.py --write` from `events/md2026_*.txt`",
        "and `common/decisions/md2026_decisions.txt`. The notes column flags content",
        "whose 2026 premise is speculative rather than a documented fact.",
        "",
        f"- Event files: **{len(by_file)}**, events: **{len(events)}**",
        f"- Decisions: **{len(decisions)}**",
        "",
    ]

    for name in sorted(by_file):
        lines.append(f"## {name}")
        lines.append("")
        lines.append("| Event | Type | Title | Date gate | MTTH | Once | Note |")
        lines.append("|---|---|---|---|---|---|---|")
        for e in by_file[name]:
            title = loc.get(e["title"], "")
            if len(title) > 70:
                title = title[:67] + "..."
            lines.append("| `{}` | {} | {} | {} | {} | {} | {} |".format(
                e["id"], e["kind"].replace("_event", ""), title, e["date"], e["mtth"],
                e["once"], note_for(e["id"])))
        lines.append("")

    lines.append("## Decisions")
    lines.append("")
    lines.append("| Decision | Date gate | Fire once | Days removed | Note |")
    lines.append("|---|---|---|---|---|")
    for d in decisions:
        lines.append("| `{}` | {} | {} | {} | |".format(
            d["id"], d["date"], d["fire_once"], d["days_remove"]))
    lines.append("")

    report = "\n".join(lines)
    if args.write:
        out = os.path.join(REPO, "docs", "Event-Audit.md")
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write(report)
        print(f"wrote {os.path.relpath(out, REPO)}: {len(events)} events, "
              f"{len(decisions)} decisions, {len(by_file)} files")
    else:
        print(report)


if __name__ == "__main__":
    main()
