"""Markdown report formatter (for PR comments and GitHub Step Summary)."""
from __future__ import annotations
from .models import ValidationReport, Issue, Severity


_STATUS_BADGE = {
    True:  "✅ **PASSED**",
    False: "❌ **FAILED**",
}

_MAX_ISSUES_PER_FILE = 20
_MAX_FILES_IN_SUMMARY = 30


def format_markdown(report: ValidationReport, detailed: bool = True) -> str:
    lines: list[str] = []

    status = _STATUS_BADGE[report.passed]
    lines.append(f"## HoI4 Mod Validator — {status}")
    lines.append("")
    lines.append(f"**Scanned:** `{report.submod_path}`  ")
    lines.append(f"**Time:** {report.timestamp}")
    lines.append("")

    # Summary table
    lines.append("### Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Files scanned | {report.files_scanned} |")
    lines.append(f"| ❌ Errors | {report.error_count} |")
    lines.append(f"| ⚠️ Warnings | {report.warning_count} |")
    lines.append(f"| ℹ️ Info/Hints | {report.info_count} |")
    lines.append(f"| Parse errors | {len(report.parse_errors)} |")
    lines.append("")

    if not report.issues and not report.parse_errors:
        lines.append("*No issues found. Mod is valid!* 🎉")
        return "\n".join(lines)

    # Issues by severity group
    if report.error_count > 0:
        lines.append("### ❌ Errors")
        lines.append("")
        _append_issues_table(lines, [i for i in report.issues if i.severity == Severity.ERROR])
        lines.append("")

    if report.warning_count > 0:
        lines.append("<details><summary>⚠️ Warnings ({count})</summary>".format(
            count=report.warning_count))
        lines.append("")
        _append_issues_table(lines, [i for i in report.issues if i.severity == Severity.WARNING])
        lines.append("</details>")
        lines.append("")

    info_issues = [i for i in report.issues
                   if i.severity in (Severity.INFO, Severity.HINT)]
    if info_issues:
        lines.append("<details><summary>ℹ️ Info/Hints ({count})</summary>".format(
            count=len(info_issues)))
        lines.append("")
        _append_issues_table(lines, info_issues)
        lines.append("</details>")
        lines.append("")

    if report.parse_errors:
        lines.append("<details><summary>🔴 Parse Errors ({count})</summary>".format(
            count=len(report.parse_errors)))
        lines.append("")
        for err in report.parse_errors:
            lines.append(f"- `{err}`")
        lines.append("</details>")
        lines.append("")

    # Issue codes breakdown
    by_code = report.issues_by_code()
    if by_code:
        lines.append("<details><summary>📊 Issues by code</summary>")
        lines.append("")
        lines.append("| Code | Count | Description |")
        lines.append("|------|-------|-------------|")
        for code, issues in sorted(by_code.items(), key=lambda kv: -len(kv[1])):
            lines.append(f"| `{code}` | {len(issues)} | {issues[0].message[:80]} |")
        lines.append("</details>")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [hoi4-mod-validator](https://github.com/)*")
    return "\n".join(lines)


def _append_issues_table(lines: list[str], issues: list[Issue]) -> None:
    lines.append("| File | Line | Code | Message |")
    lines.append("|------|------|------|---------|")
    for issue in issues[:_MAX_ISSUES_PER_FILE * _MAX_FILES_IN_SUMMARY]:
        file_short = issue.file.split("/")[-1] if "/" in issue.file else issue.file
        msg = issue.message.replace("|", "\\|")[:120]
        lines.append(f"| `{file_short}` | {issue.line} | `{issue.code}` | {msg} |")
    if len(issues) > _MAX_ISSUES_PER_FILE * _MAX_FILES_IN_SUMMARY:
        lines.append(f"| ... | ... | ... | *{len(issues) - _MAX_ISSUES_PER_FILE * _MAX_FILES_IN_SUMMARY} more issues* |")


def write_markdown(report: ValidationReport, output_path: str) -> None:
    from pathlib import Path
    Path(output_path).write_text(format_markdown(report), encoding="utf-8")
